---
logging:
  level: INFO
  loggers:
    org.example: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: khushal
  password: khushal0225
  url: jdbc:mysql://mysql:3306/db_tasks
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

